In [ ]:
#Soniyning ro'yxatini bir o'lchovli NumPy massiviga aylantirish uchun NumPy dasturini yozing.
import numpy as nb
my_list= [12.23, 13.32, 100, 36.32]
my_arr=nb.array(my_list)

my_arr

array([ 12.23,  13.32, 100.  ,  36.32])

In [3]:
import numpy as np

# Create an array with values from 2 to 10
arr = np.arange(2, 11)

# Reshape it into a 3x3 matrix
matrix = arr.reshape(3, 3)

print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [61]:
import numpy as np

# Null vector yaratamiz (0 lar bilan)
nol = np.zeros(10)

print("Boshlang'ich:", nol)

# 6-chi qiymatni yangilash (index = 5)
nol[5] = 11

print("Yangilangan:", nol)


Boshlang'ich: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Yangilangan: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [62]:
#Write a NumPy program to create an array with values ranging from 12 to 38.

num=nb.arange(12,38)
num

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [63]:
import numpy as np

# Original array (butun sonlar)
arr = np.array([1, 2, 3, 4])
print("Original array:", arr)
print("Original data type:", arr.dtype)

# Arrayni float ga aylantirish
float_arr = arr.astype(float)
print("Float array:", float_arr)
print("Float data type:", float_arr.dtype)


Original array: [1 2 3 4]
Original data type: int64
Float array: [1. 2. 3. 4.]
Float data type: float64


In [5]:
import numpy as np  # NumPy kutubxonasini chaqiramiz

# Selsiydagi haroratlar ro'yxati
centigrade = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.])

# Selsiydan Farangeytga o'tkazamiz
fahrenheit = (9/5) * centigrade + 32

# Natijalarni chiqaramiz
print("Selsiy darajalari:", centigrade)
print("Farangeyt darajalari:", fahrenheit)


Selsiy darajalari: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Farangeyt darajalari: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]


In [21]:
import numpy as nb
lis=nb.array([10,20,30])
lis
lis1=[40,50,60,70,80,90,100]
lis1

full=nb.append(lis,lis1)
full
 
 


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [76]:
# 10 elementdan iborat tasodifiy NumPy massivini yarating va massivning o'rtacha,
#  median va standart og'ishini hisoblashingiz kerak.
son=nb.random.rand(10)
son.mean()
son.cumsum()
raqam=son.argsort()
raqam

array([9, 7, 8, 3, 6, 2, 1, 4, 5, 0])

In [83]:
ran=nb.random.rand(10,10)
ran.max()
ran.min()

np.float64(0.0026850578485999588)

In [84]:
ran2=nb.random.rand(3,3,3)
ran2

array([[[0.13233835, 0.99778417, 0.85171202],
        [0.66289976, 0.4236332 , 0.36912864],
        [0.34730522, 0.54956826, 0.20169172]],

       [[0.33909393, 0.03330752, 0.26896013],
        [0.57721328, 0.74675217, 0.75352227],
        [0.82335006, 0.07119529, 0.25894087]],

       [[0.9457687 , 0.66486827, 0.68723576],
        [0.85308386, 0.89307898, 0.87203593],
        [0.72694008, 0.21297409, 0.3039177 ]]])